- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:  
     - name: install the latest version of Apache
       yum:
          name: httpd
          state: present

     - name: iam going to start apache
       service:
          name: httpd
          state: started

     - name: iam going to configure index file
       copy:
          src: ./index.html
          dest: /var/www/html/index.html
          mode: '0777'
